#====================================================#
#                                                    #
#                picom.conf sample                   #
#                                                    #
#   To learn more about how to configure picom       #
#   go to https://picom.app/                         #
#                                                    #
#====================================================#

rules: ({
  match = "class_g = 'i3bar'";
  corner-radius = 0;
  opacity = 1.0;
},{
  match = "class_g = 'firefox'";
  opacity = 1.0;
},{
  match = "focused"; opacity = 1;
},{
  match = "!focused && class_g = 'kitty'"; opacity = .6;
},{
  match = "fullscreen"; corner-radius = 0;
},{
  # DISABLING ROUNDED CORNERS FOR HOVER/POPUP WINDOWS
  match = "window_type = 'tooltip' || "
          "window_type = 'menu' || "
          "window_type = 'dropdown_menu' || "
          "window_type = 'popup_menu' || "
          "window_type = 'utility' || "
          "(class_g = 'Wine' && override_redirect = true)"
          "(class_g = 'steam_app_0' && "
          "override_redirect = true)";
  corner-radius = 0;
});

corner-radius = 20;
shadow = true;
shadow-radius = 12;
shadow-offset-x = -7;
shadow-offset-y = -7;
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;



backend = "glx"

vsync = true;
use-damage = true;
blur : {
    method = "dual_kawase";
    strength = 5;
    deviation = 10;
    size = 13;
    background = true;
    background-frame = true;
    background-fixed = true;
}
focus-exclude = ["class_g = 'i3lock-fancy-rapid'" ];
unredir-if-possible = false;
